package com.bannergress.backend.entities;

import com.bannergress.backend.security.CustomRevisionListener;
import org.hibernate.envers.RevisionEntity;
import org.hibernate.envers.RevisionNumber;
import org.hibernate.envers.RevisionTimestamp;

import javax.persistence.*;

import java.time.Instant;
import java.util.Date;

/**
 * Revision information.
 */
@Entity
@Table(name = "revision")
@RevisionEntity(CustomRevisionListener.class)
public class Revision {
    /**
     * Autogenerated revision ID.
     */
    @Id
    @Column(name = "id")
    @GeneratedValue
    @RevisionNumber
    private int id;

    /**
     * Revision creation time.
     */
    @Column(name = "created", nullable = false, columnDefinition = "timestamp with time zone")
    @RevisionTimestamp
    private Date created;

    /**
     * User who created the revision.
     */
    @Column(name = "userid", nullable = true)
    private String userid;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Instant getCreated() {
        return created == null ? null : created.toInstant();
    }

    public void setCreated(Instant created) {
        this.created = created == null ? null : Date.from(created);
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }
}
