package com.bannergress.backend.audit;

import jakarta.persistence.*;
import org.hibernate.envers.RevisionEntity;
import org.hibernate.envers.RevisionNumber;
import org.hibernate.envers.RevisionTimestamp;

import java.time.Instant;

/**
 * Revision information.
 */
@Entity
@Table(name = "revision")
@RevisionEntity(CustomRevisionListener.class)
public class Revision {
    /**
     * Autogenerated revision ID.
     */
    @Id
    @Column(name = "id")
    @GeneratedValue
    @RevisionNumber
    private int id;

    /**
     * Revision creation time.
     */
    @Column(name = "created", nullable = false)
    @RevisionTimestamp
    private Instant created;

    /**
     * User who created the revision.
     */
    @Column(name = "userid", nullable = true)
    private String userid;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Instant getCreated() {
        return created;
    }

    public void setCreated(Instant created) {
        this.created = created;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }
}
